<?php
// $Id: site_faq.module,v 1.2 2008/04/19 16:45:57 merlinofchaos Exp $
/**
 * @file
 *
 * Provide help for the site.
 */
/**
 * Implementation of hook_menu().
 */
function site_faq_menu() {
  // View help topic index.
  $items['site_faq'] = array(
    'title' => 'Site Help',
    'page callback' => 'site_faq_index_page',
    'access arguments' => array('view advanced help index'),
    'weight' => 9,
  );
  return $items;
}

function site_faq_index_page() {
  $output = theme('advanced_help_topic', 'site_faq', 'overview');
  $output .= '&nbsp;' . t('Click the help icon to launch the Site help in a pop-up window .');
  return $output;
}
